# Generated by Django 3.0.8 on 2020-09-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digital', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
