# Generated by Django 3.0.8 on 2020-09-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital', '0003_auto_20200915_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='altele',
            old_name='description',
            new_name='descriere',
        ),
        migrations.RenameField(
            model_name='altele',
            old_name='name',
            new_name='nume',
        ),
        migrations.RenameField(
            model_name='bauturi',
            old_name='description',
            new_name='descriere',
        ),
        migrations.RenameField(
            model_name='bauturi',
            old_name='name',
            new_name='nume',
        ),
        migrations.RenameField(
            model_name='desert',
            old_name='description',
            new_name='descriere',
        ),
        migrations.RenameField(
            model_name='desert',
            old_name='name',
            new_name='nume',
        ),
        migrations.RenameField(
            model_name='principal',
            old_name='description',
            new_name='descriere',
        ),
        migrations.RenameField(
            model_name='principal',
            old_name='name',
            new_name='nume',
        ),
        migrations.RemoveField(
            model_name='altele',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bauturi',
            name='price',
        ),
        migrations.RemoveField(
            model_name='desert',
            name='price',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='price',
        ),
        migrations.AddField(
            model_name='altele',
            name='pret',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bauturi',
            name='pret',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='desert',
            name='pret',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='pret',
            field=models.IntegerField(null=True),
        ),
    ]
