# Generated by Django 3.0.8 on 2020-09-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digital', '0004_auto_20200916_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
