# Generated by Django 3.0.8 on 2020-09-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digital', '0005_delete_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Altele',
        ),
    ]
